spring:
  application:
    name: parkingmanager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parkingmanager?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    propreties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false